# Generated by Django 5.1 on 2025-05-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='name',
        ),
        migrations.RemoveField(
            model_name='handyman',
            name='name',
        ),
        migrations.RemoveField(
            model_name='logistic',
            name='name',
        ),
        migrations.AddField(
            model_name='engine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='e_images/'),
        ),
        migrations.AddField(
            model_name='handyman',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='h_images/'),
        ),
        migrations.AddField(
            model_name='logistic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='l_images/'),
        ),
    ]
