# Generated by Django 5.1 on 2025-06-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appone", "0002_remove_engine_name_remove_handyman_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engine",
            name="image_alt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text"
            ),
        ),
        migrations.AddField(
            model_name="engine",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="handyman",
            name="image_alt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text"
            ),
        ),
        migrations.AddField(
            model_name="handyman",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="logistic",
            name="image_alt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Image Alt Text"
            ),
        ),
        migrations.AddField(
            model_name="logistic",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
